-- Drop all existing tables to start fresh
DROP TABLE IF EXISTS "Event" CASCADE;
DROP TABLE IF EXISTS "calls" CASCADE;
DROP TABLE IF EXISTS "emails" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "prospects" CASCADE;
DROP TABLE IF EXISTS "tasks" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Drop all enums
DROP TYPE IF EXISTS "CallOutcome" CASCADE;
DROP TYPE IF EXISTS "CallStatus" CASCADE;
DROP TYPE IF EXISTS "EmailStatus" CASCADE;
DROP TYPE IF EXISTS "EmailType" CASCADE;
DROP TYPE IF EXISTS "AccountStatus" CASCADE;
DROP TYPE IF EXISTS "ProspectStatus" CASCADE;
DROP TYPE IF EXISTS "EventType" CASCADE;
DROP TYPE IF EXISTS "TaskPriority" CASCADE;
DROP TYPE IF EXISTS "TaskStatus" CASCADE;
DROP TYPE IF EXISTS "TaskType" CASCADE;
