-- AlterTable
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "targetEmails" INTEGER NOT NULL DEFAULT 40;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "targetCalls" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "targetLeads" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "targetLinkedin" INTEGER NOT NULL DEFAULT 20;
